### ISSUE TITLE
Custom pre-commit command

### ISSUE THREAD

**Issue by gildebrand** [sugatpoudel/git-deploy#1]
Thank you for this Github Action. I have a feature suggestion and request.

**Background**
I'm using it to upload the build artefacts to a repository when an Angular project is updated, and it works great. I'm only having one minor issue; the build process generates files with new names for each build (file names includes a hash of the file), and because of this more and more files are added to the repository for each build.

**Suggestion**
Add a field to the action, allowing the user to specify a custom command after checkout out the repository, but before copying changes to the repository. This way, I could add a command like `git rm -r *` to clear the repository before adding the new files.

**Comment by tagus** [comment]
Hello gildebrand, this problem has been actually been creeping up in a couple of my own repos due to stale build artifacts for a while now. I finally got around at attempting to fix this in [v0.3.2](https://github.com/tagus/git-deploy/releases/tag/v0.3.2) by adding a new boolean param `clean_repo` to this action.  

Basically I'm optionally specifying a `--delete` flag to the `rsync` command that moves the updates to the repo. This should remove all files in the repo that are not in the `changes` directory. I thought this was a bit tighter than specfying an arbitrary command hook. 

Please give it a try and let me know if you run into any further issues. ty

**Comment by tagus** [comment]
closing this issue since the original problem was *hopefully* addressed
