### ISSUE TITLE
Rsync symbolic links in deploy

### ISSUE THREAD

**Issue by bmcfee** [sugatpoudel/git-deploy#3]
I'm setting up a deployment that includes a dynamically constructed symbolic link in the file tree; think something like `latest -> $(git tag -l |tail -1)`.  This all works fine in my build, but the git-deploy action is skipping the symlink because of the following rsync line:

https://github.com/tagus/git-deploy/blob/c7de901f0c7d498fefa2dbddf99290a5b3015550/entrypoint.sh#L51

resulting in the following output:
```
checking out branch: main
/github/workspace/repo /github/workspace
Already on 'main'
Your branch is up to date with 'origin/main'.
/github/workspace
copying changes
sending incremental file list
skipping non-regular file "latest"
...
```

Would you be open to changing this rsync to include the option `--links`?  (Or, more conservatively, -a for archive mode?)

Or would it be better to add an environment variable for additional rsync parameters?

**Comment by tagus** [comment]
Hi Brian,

Sorry for the late response; I was trying to get a better understanding for all the options associated with archive mode. I was a bit worried about specific flags because I want to keep this action as general as possible. However, I think `archive` mode actually fits the action's intent with rsync better than what I had before so I fully support this change.

I can handle bumping the version and deploying the action.

Found this great [SO](https://serverfault.com/questions/141773/what-is-archive-mode-in-rsync) explanation for rsync's archive mode. Putting it here for posterity.

**Comment by bmcfee** [comment]
No worries, I just opened the pr because I had some downtime yesterday. Thanks for looking into it and merging!

**Comment by bmcfee** [comment]
I just gave this a spin, and it looks like the -a change was reverted somewhere after merge?

Current (0.4) version has:
https://github.com/tagus/git-deploy/blob/fe88900309fcba62c77a5ecdf1210bd0de81bd3b/entrypoint.sh#L51

**Comment by tagus** [comment]
please try again

**Comment by bmcfee** [comment]
Works perfectly now - thanks!
